import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import React from 'react';

import styles from '../styles/Form.module.scss';

const ForgotPassword: NextPage = () => {
   const [email, setEmail] = React.useState('');
   function onSubmit(e: React.FormEvent<HTMLFormElement>) {
      e.preventDefault();
   }
   return (
      <div className={styles.container}>
         <Head>
            <title>Login</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <form className={styles.form} onSubmit={onSubmit}>
            <h2>Reset Password</h2>
            <div className={styles.group}>
               <input
                  id='email'
                  type='email'
                  placeholder='user@domain.com'
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className={styles.input}
               />
               <label htmlFor='email' className={styles.label}>
                  Email Address
               </label>
            </div>
            <button type='submit' className={styles.button}>
               Send Reset Link
            </button>
            <div className={styles.altlinks}>
               <Link href='/login'>
                  <a>Go To Login Page</a>
               </Link>
               <Link href='/signup'>
                  <a>Go To Sign Up Page</a>
               </Link>
            </div>
         </form>
      </div>
   );
};

export default ForgotPassword;
